import {readFile} from 'node:fs/promises'
import {scan, type ScanOptions} from './content/scan.ts'

function escapeHTML(text: string) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;')
}

async function asset(name: string) {
    return readFile(new URL(`./assets/${name}`, import.meta.url), 'utf8')
}

export async function createPage(directory: string, options: ScanOptions = {}) {
    const catalog = await scan(directory, options)
    const payload = JSON.stringify(catalog)
        .replaceAll('<', '\\u003c')
        .replaceAll('>', '\\u003e')
        .replaceAll('&', '\\u0026')
        .replaceAll('\u2028', '\\u2028')
        .replaceAll('\u2029', '\\u2029')
    const diagrams = catalog.documents.some(document => document.html.includes('language-mermaid'))
    const [css, js, mermaid, licenses] = await Promise.all([
        asset('site.css'),
        asset('site.js'),
        diagrams ? asset('mermaid.js') : '',
        asset('LICENSES.txt'),
    ])
    const script = (source: string) => `<script>${source.replace(/<\/script/gi, '<\\/script')}</script>`
    return `<!doctype html>
<!-- Generated by mdsite. Edit Markdown sources. -->
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHTML(catalog.title)} · 文档</title>
<script>try{document.documentElement.dataset.theme=localStorage.getItem('mdsite-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch{document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}</script>
<style>${css}</style></head><body><div id="root"></div><noscript>请启用 JavaScript 阅读文档。</noscript><script id="documentation" type="application/json">${payload}</script>${mermaid ? script(mermaid) : ''}${script(js)}<script type="text/plain" id="third-party-licenses">${escapeHTML(licenses)}</script></body></html>
`
}
